# Generated by Django 4.2.17 on 2025-02-17 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geodata',
            name='name',
        ),
    ]
