# Generated by Django 4.2.17 on 2025-02-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0002_remove_geodata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='properies',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
