# Generated by Django 4.2.17 on 2025-02-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0003_geodata_properies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geodata',
            old_name='properies',
            new_name='property',
        ),
    ]
