# Generated by Django 4.2.17 on 2025-02-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0006_changes_geo_data_geodata_is_changing'),
    ]

    operations = [
        migrations.AddField(
            model_name='changes',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
