# Generated by Django 4.2.17 on 2025-03-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0008_irandata'),
    ]

    operations = [
        migrations.AddField(
            model_name='irandata',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
