# Generated by Django 4.2.17 on 2025-03-05 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0009_irandata_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geodata',
            name='is_changing',
        ),
    ]
