# Generated by Django 4.2.17 on 2025-04-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0010_remove_geodata_is_changing'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sardar'),
        ),
    ]
