# Generated by Django 4.2.17 on 2025-04-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0011_geodata_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geojson', models.JSONField()),
            ],
        ),
    ]
