# Generated by Django 4.2.17 on 2025-04-12 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0013_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='geo_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_.geodata'),
        ),
    ]
