# Generated by Django 4.2.17 on 2025-04-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0014_documents_geo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='abstract',
        ),
    ]
