# Generated by Django 4.2.17 on 2025-04-19 07:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0015_remove_documents_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkGeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('property', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sardar')),
            ],
        ),
    ]
