# Generated by Django 4.2.17 on 2025-04-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0016_bookmarkgeo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkgeo',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
