# Generated by Django 4.2.17 on 2025-04-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0018_remove_bookmarkgeo_name_mainbookmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
