# Generated by Django 4.2.17 on 2025-04-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0019_geodata_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='name',
            field=models.CharField(default='املاک و مستغلات'),
        ),
    ]
