# Generated by Django 4.2.17 on 2025-04-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0021_usercomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geodata',
            name='name',
        ),
    ]
