# Generated by Django 4.2.17 on 2025-04-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0022_remove_geodata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainGeoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='geodata',
            name='main_geo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_.maingeodata'),
        ),
    ]
