# Generated by Django 4.2.21 on 2025-05-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0023_maingeodata_geodata_main_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='changes',
            name='persian_key',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
