# Generated by Django 4.2.21 on 2025-05-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0024_changes_persian_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
