# Generated by Django 4.2.21 on 2025-05-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_', '0025_log_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
